{
  "formatVersion": "1.1",
  "component": {
    "group": "com.munch.lib",
    "module": "weight",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "weight-0.1.0.aar",
          "url": "weight-0.1.0.aar",
          "size": 20512,
          "sha512": "669aa866a8c3e216d1df8f1fbb25084dc27657ffc1b7aa3fb03f99f664bb5d029ff23ba15cf93de3dfefb79942050b1bd4919e7f294c842db11c05266170380e",
          "sha256": "e44646b94ded562809c10ea5250d3df758a625a03b73cfb64bba1b9218ff7fed",
          "sha1": "a33d5ca293fdf934b0040a01a362569b7a6cdd03",
          "md5": "47717ec79d1d21e8b4555db345cb4f99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "weight-0.1.0.aar",
          "url": "weight-0.1.0.aar",
          "size": 20512,
          "sha512": "669aa866a8c3e216d1df8f1fbb25084dc27657ffc1b7aa3fb03f99f664bb5d029ff23ba15cf93de3dfefb79942050b1bd4919e7f294c842db11c05266170380e",
          "sha256": "e44646b94ded562809c10ea5250d3df758a625a03b73cfb64bba1b9218ff7fed",
          "sha1": "a33d5ca293fdf934b0040a01a362569b7a6cdd03",
          "md5": "47717ec79d1d21e8b4555db345cb4f99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "weight-0.1.0-sources.jar",
          "url": "weight-0.1.0-sources.jar",
          "size": 3952,
          "sha512": "58d9c1a8bc75d34bcef4209ab1053d8bd95bb1ac4d52394afd84726cda28d5379b485664fc70b56642fc1855d8b86b0758fb21709914fc93adfd32457b1d1019",
          "sha256": "a7e8d893ccbe50c69e5ae12902a3ae57eaed6a26173d9ae9460db7171b148fb1",
          "sha1": "a2385af07778c4ea1d4a8afa13d897358d1afe29",
          "md5": "9e7ea7fce0554b3ff4532736191bce97"
        }
      ]
    }
  ]
}
