{
  "formatVersion": "1.1",
  "component": {
    "group": "com.munch.lib",
    "module": "weight",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "weight-0.1.0.aar",
          "url": "weight-0.1.0.aar",
          "size": 20138,
          "sha512": "c232f228692e8a8ae1ea1378845c413bdb439b6b816f2d1f1d29aaf43dd0b58e116b8141955aa6c614fa79d8936e751fb0b6b525940922ca55fb80abdd7b6387",
          "sha256": "1492f1b76704226158506110665c4cf59dc89b3d14d6ecb81d938841c55e0c72",
          "sha1": "d6db30cca2ae2b1bd247b9104326c74e4ca6913a",
          "md5": "1da97d42fc09a242257409e847f1bbe2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "weight-0.1.0.aar",
          "url": "weight-0.1.0.aar",
          "size": 20138,
          "sha512": "c232f228692e8a8ae1ea1378845c413bdb439b6b816f2d1f1d29aaf43dd0b58e116b8141955aa6c614fa79d8936e751fb0b6b525940922ca55fb80abdd7b6387",
          "sha256": "1492f1b76704226158506110665c4cf59dc89b3d14d6ecb81d938841c55e0c72",
          "sha1": "d6db30cca2ae2b1bd247b9104326c74e4ca6913a",
          "md5": "1da97d42fc09a242257409e847f1bbe2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "weight-0.1.0-sources.jar",
          "url": "weight-0.1.0-sources.jar",
          "size": 3951,
          "sha512": "fb9dfea6815cec291c167735e4529aa6870856526401ccd9747e6220f7ceec8bee86abd4c25180c3bf6f10769a7f8810370e4eb9a89eabd71a819f756157666d",
          "sha256": "7f77486c800204d68cb4623ba89b8f380dfd27f8ff86431a7e360d008166e786",
          "sha1": "13791a17c45c818f6317820a69f3968773c910f4",
          "md5": "8d86a3e5232bbc2da243b4b3bbdac7f6"
        }
      ]
    }
  ]
}
