{
  "formatVersion": "1.1",
  "component": {
    "group": "com.munch.lib",
    "module": "libfast",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "record",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "libfast-0.2.0.aar",
          "url": "libfast-0.2.0.aar",
          "size": 88209,
          "sha512": "294203ca2236fcbf8dd9b9d6d1e008849c59e7b4539d102097baf41728ac0d2e7ccecc3dd5265094f2bff4e4c984643fa4b4b8fd8b4ee368f5f2016c4cbdc558",
          "sha256": "ee336ade56379062b053ccc047e9db8e386ef34abdef202f7f9310f5293bd928",
          "sha1": "e79625b315fb1eadb8e2ed2826b2bbb575da53d8",
          "md5": "eeb98447881585253040dd13dc99b46c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "record",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "libfast-0.2.0.aar",
          "url": "libfast-0.2.0.aar",
          "size": 88209,
          "sha512": "294203ca2236fcbf8dd9b9d6d1e008849c59e7b4539d102097baf41728ac0d2e7ccecc3dd5265094f2bff4e4c984643fa4b4b8fd8b4ee368f5f2016c4cbdc558",
          "sha256": "ee336ade56379062b053ccc047e9db8e386ef34abdef202f7f9310f5293bd928",
          "sha1": "e79625b315fb1eadb8e2ed2826b2bbb575da53d8",
          "md5": "eeb98447881585253040dd13dc99b46c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libfast-0.2.0-sources.jar",
          "url": "libfast-0.2.0-sources.jar",
          "size": 12489,
          "sha512": "6ffd14735aa29ed96d8a7d9d9baa8bef351fe43641fe5aaa7b46762984d239a986240da40e28362c8b074ea87e65658855ee6d7d4ff71bf25d921337d8146541",
          "sha256": "7368fea8be402a6ca4ee841900013f30582c2045b523c42fcb8d524e88ce9260",
          "sha1": "8571f04b623edb7f3a9d9035156c2befd8efd61e",
          "md5": "f2243cc42e56f21b20c0ef8127756c89"
        }
      ]
    }
  ]
}
