{
  "formatVersion": "1.1",
  "component": {
    "group": "com.munch.lib",
    "module": "libfast",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "record",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "libfast-0.2.0.aar",
          "url": "libfast-0.2.0.aar",
          "size": 86487,
          "sha512": "a4b3ed4968f42a05ff0b61a9f76e4c0bb0294ca7fd230db51fb7594bf711763571216c9f8451d042f38c9678ef8ccb2faab3c408ee272c6e7db2e37e5350105b",
          "sha256": "9551994cd78860b6617379900796a31eb0de05f0870339356a5152fd389e2046",
          "sha1": "895eff73f6d27fe32bfa4ae964ad20f9970432e6",
          "md5": "f9153b5f92470cc407378e3871aff07d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "record",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "libfast-0.2.0.aar",
          "url": "libfast-0.2.0.aar",
          "size": 86487,
          "sha512": "a4b3ed4968f42a05ff0b61a9f76e4c0bb0294ca7fd230db51fb7594bf711763571216c9f8451d042f38c9678ef8ccb2faab3c408ee272c6e7db2e37e5350105b",
          "sha256": "9551994cd78860b6617379900796a31eb0de05f0870339356a5152fd389e2046",
          "sha1": "895eff73f6d27fe32bfa4ae964ad20f9970432e6",
          "md5": "f9153b5f92470cc407378e3871aff07d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libfast-0.2.0-sources.jar",
          "url": "libfast-0.2.0-sources.jar",
          "size": 12400,
          "sha512": "761c909774f0c9617f5b405677c60a31807a3585ac435839f8949934267f5657f158e6685218176b75d2cdb96ef054dc1574ea161857cefed661084af5b81c8c",
          "sha256": "de309776fb5cc749b0ae4752d52c18ef2681cb00a5f127b404a0559f5dd767aa",
          "sha1": "bc408966fbd3231036258acc284c6cba73cdb243",
          "md5": "5e0017a2d2f72775472756bf69765939"
        }
      ]
    }
  ]
}
