{
  "formatVersion": "1.1",
  "component": {
    "group": "com.munch.lib",
    "module": "libfast",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "record",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "libfast-0.2.0.aar",
          "url": "libfast-0.2.0.aar",
          "size": 87526,
          "sha512": "0fd264315fd8c1bc79d2cd5152d1a364872385f0d8c6213b054ca4e8c35375f1caf41c791e9e29b1ad67e2f7c2b886218063cdff98813023cd4d62fcd38beb96",
          "sha256": "cc3415b3c24822b5803da03be34ef3892f6a7168133a575b1d2aab02475f02ff",
          "sha1": "0447b7d4cd264280e304fa21b3c816cd4c6ec44b",
          "md5": "deb6c3657f19c14d08eb484df58116fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "record",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "libfast-0.2.0.aar",
          "url": "libfast-0.2.0.aar",
          "size": 87526,
          "sha512": "0fd264315fd8c1bc79d2cd5152d1a364872385f0d8c6213b054ca4e8c35375f1caf41c791e9e29b1ad67e2f7c2b886218063cdff98813023cd4d62fcd38beb96",
          "sha256": "cc3415b3c24822b5803da03be34ef3892f6a7168133a575b1d2aab02475f02ff",
          "sha1": "0447b7d4cd264280e304fa21b3c816cd4c6ec44b",
          "md5": "deb6c3657f19c14d08eb484df58116fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libfast-0.2.0-sources.jar",
          "url": "libfast-0.2.0-sources.jar",
          "size": 12487,
          "sha512": "391c058d8fcd50189d31c0489d100e53e730ce3b85dae0945dfad8122d06637e4e9d3e2f029c5fa93a4a3544e90336fcdbf1e6f161f0b9a009dc7c7f00819eba",
          "sha256": "9b71807a73462fb19948efa2eb3dd8f3f49b1a5c8e68e748f5912449275d10ae",
          "sha1": "1f3493e6f5837cfd274774d6e4c05bb163a1a932",
          "md5": "b9bd315b063542f062a390454b163f65"
        }
      ]
    }
  ]
}
