{
  "formatVersion": "1.1",
  "component": {
    "group": "com.munch.lib",
    "module": "lib",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.2.0.aar",
          "url": "lib-0.2.0.aar",
          "size": 345558,
          "sha512": "25c366a989f37f605b362f88e7e65540e2dc7db76ed5d371722617809bee9ae6d19615cdd093921d77db099c3e79a944b7215c792af76809cfa21a11e56b40d5",
          "sha256": "aca600ca11e68f9611444301ff24997a3482246fcabc24182cb82181f43c4380",
          "sha1": "389a3d1667cc74d4a17e58963714c4007e47fcfb",
          "md5": "3db28c6f47ef44b5b50dabc1bbe43da9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.2.0.aar",
          "url": "lib-0.2.0.aar",
          "size": 345558,
          "sha512": "25c366a989f37f605b362f88e7e65540e2dc7db76ed5d371722617809bee9ae6d19615cdd093921d77db099c3e79a944b7215c792af76809cfa21a11e56b40d5",
          "sha256": "aca600ca11e68f9611444301ff24997a3482246fcabc24182cb82181f43c4380",
          "sha1": "389a3d1667cc74d4a17e58963714c4007e47fcfb",
          "md5": "3db28c6f47ef44b5b50dabc1bbe43da9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lib-0.2.0-sources.jar",
          "url": "lib-0.2.0-sources.jar",
          "size": 61478,
          "sha512": "0225f92c2c5a14a9cf2ddd4e48a8f1b81bc1b8f0018c59fc81f351e798a2c1a9eb72fa222fe633a8478102bccaf642e02fa3afedb1dd6d2cbb8bd25ea92a8221",
          "sha256": "d1b5f806fedd6dbb4252c7db2832425d25fa12cfff67b0e5e7dfc33c51764b0d",
          "sha1": "200e8e4a0367658bda32aed364039fccf5d866bf",
          "md5": "3dabb702caa829f479af69e760b11809"
        }
      ]
    }
  ]
}
