{
  "formatVersion": "1.1",
  "component": {
    "group": "com.munch.lib",
    "module": "lib",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.2.0.aar",
          "url": "lib-0.2.0.aar",
          "size": 338830,
          "sha512": "30c2c8909d500fcdb035928923d5bddfebe36e35d42c65d835a38f4d4be1547116003043638665e22b373866545b977003045f39faf69b69aca56f89f1693af9",
          "sha256": "4bcd6743a128feb7b9051c2aca7f29e97206e0df2e4927b28b620cf51ce11129",
          "sha1": "9f1ce49fe6a39093f46f910c48120fb6fd02d5ef",
          "md5": "6a39015a0aab8c49ca0a77e6667dd2d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.2.0.aar",
          "url": "lib-0.2.0.aar",
          "size": 338830,
          "sha512": "30c2c8909d500fcdb035928923d5bddfebe36e35d42c65d835a38f4d4be1547116003043638665e22b373866545b977003045f39faf69b69aca56f89f1693af9",
          "sha256": "4bcd6743a128feb7b9051c2aca7f29e97206e0df2e4927b28b620cf51ce11129",
          "sha1": "9f1ce49fe6a39093f46f910c48120fb6fd02d5ef",
          "md5": "6a39015a0aab8c49ca0a77e6667dd2d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lib-0.2.0-sources.jar",
          "url": "lib-0.2.0-sources.jar",
          "size": 60519,
          "sha512": "144dd844288c4562b45db94e3c266a78d996dad5bd1a438d2ce9cdb8dbdfe7891b03ea9636b02738d55d914e4e812a735ac5930fc88b61d2397fb9457f116308",
          "sha256": "d1c4da2dd17a75e78350271e562df48953bcadd366f72a810270edbcfe4fc4a2",
          "sha1": "a07d5355519de1551eca0fb2a109650f84b1d393",
          "md5": "34e680fc8ec83ed8598fec39bf516e05"
        }
      ]
    }
  ]
}
