{
  "formatVersion": "1.1",
  "component": {
    "group": "com.munch.lib",
    "module": "lib",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.2.0.aar",
          "url": "lib-0.2.0.aar",
          "size": 333419,
          "sha512": "c72e1ed25ec7e5598bfce7598fd96560b7d7f2d75bde49b21b342d8e122badd8346603afcc20fa4deb195500d4075492d20a5621b5bf739d10a2629c8dd76c8b",
          "sha256": "4609bb9b07f8a5369d2d9f4b22c376327ac01b0321f66df2f1ab896d14fc432d",
          "sha1": "b122fe40075c9d5f86647c32c3eef0d748fc6c8b",
          "md5": "577287dd841c6605a4b6c6061cb4dd90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.2.0.aar",
          "url": "lib-0.2.0.aar",
          "size": 333419,
          "sha512": "c72e1ed25ec7e5598bfce7598fd96560b7d7f2d75bde49b21b342d8e122badd8346603afcc20fa4deb195500d4075492d20a5621b5bf739d10a2629c8dd76c8b",
          "sha256": "4609bb9b07f8a5369d2d9f4b22c376327ac01b0321f66df2f1ab896d14fc432d",
          "sha1": "b122fe40075c9d5f86647c32c3eef0d748fc6c8b",
          "md5": "577287dd841c6605a4b6c6061cb4dd90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lib-0.2.0-sources.jar",
          "url": "lib-0.2.0-sources.jar",
          "size": 60221,
          "sha512": "df7a90e8b2ca59dacee704256a01d58a3dcdc62f7ecac8e37af703d70f45b77f62777ccbfc94636a8c30d90d799e21c64e057546b6e160078b146851cd6e09c4",
          "sha256": "d143d53cfce8632fd97837d40bfe996d7e916e6642be7bdf137f182e94eaae5b",
          "sha1": "540ce6061a9ac16479cf9286fb1e72c1957c696d",
          "md5": "9f09918c1a8a1e63b26c2d4dce2d670c"
        }
      ]
    }
  ]
}
