{
  "formatVersion": "1.1",
  "component": {
    "group": "com.munch.lib",
    "module": "record",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "record-0.1.0.aar",
          "url": "record-0.1.0.aar",
          "size": 37983,
          "sha512": "4815690c1871192b0505ad6489ecb991d8480d990d3c31aa38a43ac22a7837ab38923581df2ee99c32ac2127edc7371ab82f2ee1b2bed1d3344aedd6d915e94f",
          "sha256": "6a49df4c5e97eb95f84764bfbd04d748af93f4c2f4e549c25030578dc691445b",
          "sha1": "25ff0d8297186ac018fdd50fa4aa727b4617ef89",
          "md5": "03d415096decd3d7c38065ee175457c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.munch.lib",
          "module": "lib",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-0.1.0.aar",
          "url": "record-0.1.0.aar",
          "size": 37983,
          "sha512": "4815690c1871192b0505ad6489ecb991d8480d990d3c31aa38a43ac22a7837ab38923581df2ee99c32ac2127edc7371ab82f2ee1b2bed1d3344aedd6d915e94f",
          "sha256": "6a49df4c5e97eb95f84764bfbd04d748af93f4c2f4e549c25030578dc691445b",
          "sha1": "25ff0d8297186ac018fdd50fa4aa727b4617ef89",
          "md5": "03d415096decd3d7c38065ee175457c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "record-0.1.0-sources.jar",
          "url": "record-0.1.0-sources.jar",
          "size": 7505,
          "sha512": "20b1ad63673426d8568c72ef0488d3fd05c1394c30633b9372544dcb65ca8ab71549e7d49e008cbb1903c42b7d14ae87ab911e857332c7f85ec74d7e3673e083",
          "sha256": "32cc3ad3ea43eb6fd011a20168ef132ec34ed26f6003c2c58acaf65b966bedd4",
          "sha1": "aafebf4ea4a73dfdabcaa72f6cb953320ac4b564",
          "md5": "2515e92f81f43c59d5fff7517b31b6bd"
        }
      ]
    }
  ]
}
